apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: release-i-0f886-deaa639
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-27
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: release-i-0f886-deaa639
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.24"
  managementCluster:
    name: release-i-0f886-deaa639
  workerNodeGroupConfigurations:
  - count: 3
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: release-i-0f886-deaa639
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-staging-eks-a-test-1abd33a1-96d8-4f94-a657-6391b8016c57-62
  clusterConfigPath: aws-staging-eks-a-test-1abd33a1-96d8-4f94-a657-6391b8016c57-62
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-staging-eks-a-test-1abd33a1-96d8-4f94-a657-6391b8016c57-62.git
  systemNamespace: default

---
